# Generated by Django 6.0.3 on 2026-03-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_orderitem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='ShippingPrice',
            new_name='shippingPrice',
        ),
    ]
